name: streaming_asr
description: Sherpa ONNX Voice Assistant
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  path: ^1.9.0
  permission_handler: ^11.3.1

  # IMPORTANT: Using latest version to fix Linux build error
  record: ^6.1.2
  
  audioplayers: ^6.0.0
  sherpa_onnx: ^1.12.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tiny-encoder.int8.onnx
    - assets/tiny-decoder.int8.onnx
    - assets/tokens.txt
    - assets/hi_IN-pratham-medium.onnx
    - assets/hi_IN-pratham-medium.onnx.json
    - assets/espeak-ng-data/